### ISSUE TITLE
ModuleNotFoundError: No module named 'click'

### ISSUE THREAD

**Issue by BDhackers009** [thenurhabib/scancss#1]
![IMG_20220314_012833](https://user-images.githubusercontent.com/67186139/158075863-4fb3bace-dcab-4fab-8a85-308543450383.jpg)

As you can see in the screenshot its showing an error called "__ModuleNotFoundError__" it is because you didnt add the **"click"** python module in the requirements.txt. Please consider adding this **click** module in requirements.txt and kindly forgive my horrible English.

Thanks.

**Comment by thenurhabib** [comment]
Thanks for your information
 I'll do it.
